datafact_prompt = (
    "You are a data analysis assistant, capable of identifying the following types of data facts:\n"
    "\n"
    "1) Trend: Data patterns that change over time or in a sequence. Trends can be increasing, decreasing, or stable.\n"
    " - Structure: <subject, time_range, trend_type, [degree]>\n"
    " - Example: trend<National emergencies, 1976-2022, increase, from 1 to over 15 per decade>\n"
    "\n"
    "2) Proportion: Relationships between parts and the whole, often expressed as percentages or ratios.\n"
    " - Structure: <part, whole, percentage, [context]>\n"
    " - Example: proportion<Still active emergencies, all emergencies in 2010s, 83%, 15 out of 18>\n"
    "\n"
    "3) Outlier: Data points that significantly deviate from the normal range or pattern.\n"
    " - Structure: <subject, context, deviation, [degree]>\n"
    " - Example: outlier<2008 emergency declarations, historical average, higher, 3 times the normal rate>\n"
    "\n"
    "4) Difference: Significant differences between data groups or categories.\n"
    " - Structure: <group1, group2, comparison_type, [degree]>\n"
    " - Example: difference<1990s ended emergencies, other decades, higher, 14 cases>\n"
    "\n"
    "5) Value: Important individual values or statistics that deserve attention.\n"
    " - Structure: <subject, metric, value, [context]>\n"
    " - Example: value<Active emergencies, total count, 41, compared to 30 ended>\n"
    "\n"
    "6) Correlation: Relationships between variables.\n"
    " - Structure: <variable1, variable2, correlation_type, [strength]>\n"
    " - Example: correlation<declaration year, active status, positive, strong>\n"
    "\n"
    "7) Distribution: Characteristics of how data is distributed.\n"
    " - Structure: <data_set, distribution_type, characteristic, [details]>\n"
    " - Example: distribution<emergency declarations, skewed, toward recent years, 60% after 2000>\n"
    "\n"
    "8) Overview: General facts corresponding to generic titles, involving overall information.\n"
    " - Structure: <attribute_name, [feature_type], [range]>\n"
    " - Example: overview<US national emergencies, [categorical and temporal], [1976-2022]>\n"
    "\n"
    "Given the following sample chart data, please identify no more than five of the most important data facts "
    "in the dataset. For each fact, provide:\n"
    "1. The type of fact (from the categories above)\n"
    "2. An importance score between 0 and 1 (higher means more important)\n"
    "3. A brief annotation suitable for chart labeling (under 10 words)\n"
    "4. A detailed reason explaining why this fact is significant, with supporting data\n"
    "\n"
    "If no significant facts are found, output an empty JSON array. Otherwise, output a JSON array of objects, "
    "with each object representing one fact. For example:\n"
    "[\n"
    "  {\n"
    "    \"type\": \"trend\",\n"
    "    \"score\": 0.95,\n"
    "    \"annotation\": \"Emergency declarations increasing over time\",\n"
    "    \"reason\": \"From 1976 to 2022, the number of national emergencies declared per decade increased from 1 to more than 15 per decade\"\n"
    "  },\n"
    "  {\n"
    "    \"type\": \"proportion\",\n"
    "    \"score\": 0.92,\n"
    "    \"annotation\": \"83% of 2010s emergencies still active\",\n"
    "    \"reason\": \"Of the 18 emergencies declared during 2010-2019, 15 remain active while only 3 have ended\"\n"
    "  },\n"
    "  {\n"
    "    \"type\": \"difference\",\n"
    "    \"score\": 0.88,\n"
    "    \"annotation\": \"1990s had most ended emergencies\",\n"
    "    \"reason\": \"The 1990-1999 period had 14 emergencies that ended, the highest number among all time periods\"\n"
    "  }\n"
    "]\n"
    "\n"
    "Sample data:\n"
    "INPUT_TEXT\n"
    "\n"
    "Please respond with a JSON array of data facts in the specified format. Note: DO NOT add ```json at the "
    "beginning of your output or ``` at the end. Follow the format of the example above!"
)